GET http://localhost:4004/odata/v4/gv-tracker/CustomerSet

### Create a New Customer
POST http://localhost:4004/odata/v4/gv-tracker/CustomerSet
Content-Type: application/json

{
    "name": "omi2",
    "email": "omi2@example.com",
    "phone" : 9552091741,
    "type_code": "Mall",
    "salutation_code" : "MR",
    "phoneCode" : 91,
    "shoppingMall_plant": 8208
}


###
GET http://localhost:4004/odata/v4/gv-tracker/GiftVoucherSet?$expand= assignGiftVouchers

###
GET http://localhost:4004/odata/v4/gv-tracker/GVHeaderSet?$expand=customer,bills,assignGiftVouchers,campaign
###
GET http://localhost:4004/odata/v4/gv-tracker/GVHeaderSet?$filter=customer/email eq 'omkarparhad88pro@gmail.com'

### Create a New Gift Voucher
POST http://localhost:4004/odata/v4/gv-tracker/GVHeaderSet
Content-Type: application/json

{
    "gv_no": 10000008,
    "total_gift_amout": 2000.00,
    "campaign": "VALENTINE SALES 2025",
    "comment": "",
    "shoppingMall_plant": 8208,
    "customer": "omkarparhad88pro@gmail.com",
    "employee": 102312,
    "gr_type_code":"CI",
    "bills": [
        {
          "no": "Bjjuu8",
          "sr_no": 1,
          "amount": 2000,
          "doc_name": "testr.pdf",
          "base64": "ydfghjuytredhjuytrdjiuytredfghuytrd",
          "mime_type_code": "PDF"
        }
    ],
    "assignGiftVouchers": [
        {
         "quantity": 1, 
         "total_amount" : 2000.00,
         "giftVoucher_ID" : "5e0d360f-69b9-4029-9ef2-a5d0be9980bd"
        }
    ]
}